[package]
name = "posthog-rs"
license = "MIT"
version = "0.2.6"
authors = ["christos <christos@openquery.io>"]
description = "An unofficial Rust client for Posthog (https://posthog.com/)."
repository = "https://github.com/openquery-io/posthog-rs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.3", default-features = false, features = ["blocking", "rustls-tls"] }
serde = { version = "1.0.125", features = ["derive"] }
chrono = {version = "0.4.19", features = ["serde"] }
serde_json = "1.0.64"
semver = "1.0.24"
os_info = "3"
uuid = { version = "1.11.0", features = ["v4", "serde"] }

[dev-dependencies]
dotenv = "0.15.0"
ctor = "0.1.26"

[features]
e2e-test = []
